### ISSUE TITLE
Handbook

### ISSUE THREAD

**Issue by JoshuaBonn1** [JoshuaBonn1/MuseScore#16]
@ericfont I've started writing up the timeline handbook page: https://musescore.org/en/node/245526
I was hoping for a bit of direction on how to write it up. I was about to go read some other pages to get myself up to speed.
Basically, the link has an outline (or at least a list) of all the things I need to add to the page. However, at the top it says:
_-Explanation of display_
_-Explanation of interaction_
_OR_
_-Mix the explanations of display and interaction when smart_
I was wondering what you thought was the better way to do it: fully explain the visuals and the interaction as separate things, or fully explain the visuals and interactions at the same time (say explain the selection of meta values at the same time I am explaining the visuals of the meta rows)

**Comment by JoshuaBonn1** [comment]
For some reason I can't get on to IRC so I'm using this for the now.

**Comment by ericfont** [comment]
I don't have a preference and I don't think it matters.  I would lean towards mixing.

**Comment by ericfont** [comment]
I see what you wrote one https://musescore.org/en/node/245526 ...the text you wrote is fine but I would think you will need to include screenshots and I think you will need to have the headers in larger size.  I also am sortof leaning to have scrolling first then zooming then the rest, since at the most basic level the user will need to scroll the timeline.

**Comment by JoshuaBonn1** [comment]
Yeah, that was mostly to get the words down. The code is taking sometime to compile (something to do with being on a different network or something) so I haven't got the screen captures yet. When I add pictures, i will fix the headers as well

**Comment by ericfont** [comment]
"Short explanation" I would just say "Overview"

"Dragging" you are using a separate heading for that.  I think "Dragging" should instead just be a bullet point inside of "Scrolling" since it really just another way to scroll.

congratulations on getting the pull request merged...

**Comment by ericfont** [comment]
btw, if compile is taking a long time, you can just download the nightly build http://ftp.osuosl.org/pub/musescore/nightlies/windows/MuseScoreNightly-2017-08-17-1418-master-49cf62c.7z

**Comment by ericfont** [comment]
You use the word "cell" but never really define it...what i would do is when you write " There are four parts to the timeline: meta labels, instrument labels, meta rows, and the main grid" I would break that up into 4 bullets starting with their position and short description, so the last one instead of just "and the main grid" I would say something along the lines of "Bottom Right: the main grid of cells representing presence of notes for a particular instrument and measure".

**Comment by ericfont** [comment]
For Ctrl selected, you write: "If no cells are currently selected, holding [Ctrl] and selecting a cell will select all cells above and below that cell in the same measure."  I would just say "...will select the *entire* measure".

I would also a short sentence at beginning of "Basic Interaction" stating that the same commands for selecting measures in the regular scoreview apply to the timeline.
