### ISSUE TITLE
Show interaction with hidden instruments

### ISSUE THREAD

**Issue by JoshuaBonn1** [JoshuaBonn1/MuseScore#3]
One last thing, if I click on a cell that belongs to a hidden instrument, nothing happens. Of course it doesn't make sense to select a measure of a hidden instrument. However, I believe that musescore should respond in some way. I say that you should still navigate the score view to that measure number. Also there should be some visual indication that select is specifically not supposed to work. I would imagine maybe some sort of grey box for that cell. That way user knows that there isn't some problem with their mouse clicker, but rather that the program is indeed detecting the clicks but the color of grey suggests the inability to actually select the measure.

**Comment by JoshuaBonn1** [comment]
So, navigating to the correct location in the score will be easy; however, I'm wondering exactly how a gray square would act in multiple different scenarios. A simple click would be handled by the grayed out box. A selection that spans above and below a hidden instrument would not include the hidden instrument in the selection. A drag selection would not include the hidden instrument. The two I am unsure about is a selection starting from a hidden instrument or ending on a hidden instrument. 

1) So, if you select a hidden instrument (which gives you a gray box) and then [Shift]+[Click] on a visible instrument, say, two instruments below, what selection is given? 

2) On the other hand, what if you select a visible instrument (which gives you a blue box) and then [Shift]+[Click] on a non visible instrument?

**Comment by ericfont** [comment]
"A simple click would be handled by the grayed out box." yes.
"A selection that spans above and below a hidden instrument would not include the hidden instrument in the selection." yes. already does this.
"A drag selection would not include the hidden instrument." yes. already does this. 

1. "So, if you select a hidden instrument (which gives you a gray box) and then [Shift]+[Click] on a visible instrument, say, two instruments below, what selection is given?"

I would say you shouldn't be able to select any range starting from a hidden instrument.  Precisely because it is not possible to select a measure in a hidden instrument in the first place.  Currently this is not possible to do, so nothing needs to change for this.

2. "On the other hand, what if you select a visible instrument (which gives you a blue box) and then [Shift]+[Click] on a non visible instrument?"

Similarly, since it is and shall not be possible to select a hidden instrument measure, then nothing shall happen upon doing the [Shift]+[Click] on a non-visible instrument measure.  Currently this is not possible to do, so nothing needs to change for this.

So all that really is needed is the grey box to appear while the left mouse button is depressed.

**Comment by JoshuaBonn1** [comment]
@ericfont Another option is to cause the cursor to change to an invalid symbol upon mousing over those cells. Like the Qt::ForbiddenCursor. 
![](http://doc.qt.io/qt-4.8/images/cursor-forbidden.png)
I do think that would be a bit more obvious and would avoid any confusion of an extra box. (Not saying there would be confusion, just that this solution might just be a bit more clean).

**Comment by ericfont** [comment]
Ok, that works too.
