### ISSUE TITLE
Scrolling through the timeline should update the instrument names like continuous view

### ISSUE THREAD

**Issue by JoshuaBonn1** [JoshuaBonn1/MuseScore#6]
Currently, if there is an instrument change in the middle of the score, the timeline ignores it.
In continuous view, as you scroll past different changes the info at the beginning changes to be accurate.
The idea is to have this happen in the timeline as well.

This is listed as an feature because I'm not planning to implement these kind of things before my next PR.

**Comment by ericfont** [comment]
no need to implement this before next PR.

I believe you will need to look for instrument change elements while scanning through the score.

I'm wondering if there should be any sort of visual indicator in the timeline cells for these instrument changes.  They probably will be very rare.  Since they only apply to particular parts, they don't belong to the entire system, so they probably don't deserve to be on a meta row.  Maybe just write the name of the new instrument starting on the first cell of the instrument change.
